services:
  php:
    image: "empaphy/php"
    build:
      context: docker
    environment:
      COMPOSER: 'composer.json'
      COMPOSER_VENDOR_DIR: 'vendor'
      COMPOSER_HOME: '/home/ubuntu/.composer'
      PHP_CS_FIXER_IGNORE_ENV: '1'
    command: [ 'sleep', 'infinity' ]
    volumes:
      - { type: bind, source: '.',              target: '/usr/src/app' }
      - { type: bind, source: "${COMPOSER_HOME:-~/.composer}", target: '/home/ubuntu/.composer' }
